configuration: Release
branches:
  only:
    - develop

before_build:
  - dotnet restore src/Autofac.Extras.NLog.sln
  - nuget restore src/Autofac.Extras.NLog.sln

build:
  project: src/Autofac.Extras.NLog.sln      
  verbosity: minimal
  
test:
  assemblies:
    - '**\*.Tests.dll'
